2024-04-29 15:33:00 ERROR Elements not present after 0.5 seconds on page: https://capital.com/trading/platform/
2024-04-29 15:33:00 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 86, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 305, in element_is_visible
    return Wait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x563b7ab51cb3 <unknown>
#1 0x563b7a8404a7 <unknown>
#2 0x563b7a88b31d <unknown>
#3 0x563b7a88b3d1 <unknown>
#4 0x563b7a8ce734 <unknown>
#5 0x563b7a8ad43d <unknown>
#6 0x563b7a8cbbe9 <unknown>
#7 0x563b7a8ad1b3 <unknown>
#8 0x563b7a87e24a <unknown>
#9 0x563b7a87ec1e <unknown>
#10 0x563b7ab15fdb <unknown>
#11 0x563b7ab19f2b <unknown>
#12 0x563b7ab020f1 <unknown>
#13 0x563b7ab1aa92 <unknown>
#14 0x563b7aae6faf <unknown>
#15 0x563b7ab40e08 <unknown>
#16 0x563b7ab40fe0 <unknown>
#17 0x563b7ab50e04 <unknown>
#18 0x7f9c75e94ac3 <unknown>

2024-04-29 15:33:03 ERROR Elements not present after 0.5 seconds on page: https://capital.com/trading/platform/
2024-04-29 15:33:03 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 86, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 305, in element_is_visible
    return Wait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x563b7ab51cb3 <unknown>
#1 0x563b7a8404a7 <unknown>
#2 0x563b7a88b31d <unknown>
#3 0x563b7a88b3d1 <unknown>
#4 0x563b7a8ce734 <unknown>
#5 0x563b7a8ad43d <unknown>
#6 0x563b7a8cbbe9 <unknown>
#7 0x563b7a8ad1b3 <unknown>
#8 0x563b7a87e24a <unknown>
#9 0x563b7a87ec1e <unknown>
#10 0x563b7ab15fdb <unknown>
#11 0x563b7ab19f2b <unknown>
#12 0x563b7ab020f1 <unknown>
#13 0x563b7ab1aa92 <unknown>
#14 0x563b7aae6faf <unknown>
#15 0x563b7ab40e08 <unknown>
#16 0x563b7ab40fe0 <unknown>
#17 0x563b7ab50e04 <unknown>
#18 0x7f9c75e94ac3 <unknown>