2024-02-06 09:19:55 ERROR Elements not present after 0.5 seconds on page: https://capital.com/de/aktienhandel
2024-02-06 09:19:55 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 299, in element_is_visible
    return Wait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x560e921eed93 <unknown>
#1 0x560e91ed2337 <unknown>
#2 0x560e91f1dd60 <unknown>
#3 0x560e91f1de51 <unknown>
#4 0x560e91f61bc4 <unknown>
#5 0x560e91f4046d <unknown>
#6 0x560e91f5f12d <unknown>
#7 0x560e91f401e3 <unknown>
#8 0x560e91f10135 <unknown>
#9 0x560e91f1113e <unknown>
#10 0x560e921b2e4b <unknown>
#11 0x560e921b6dfa <unknown>
#12 0x560e9219f6d5 <unknown>
#13 0x560e921b7a6f <unknown>
#14 0x560e9218369f <unknown>
#15 0x560e921dc098 <unknown>
#16 0x560e921dc262 <unknown>
#17 0x560e921edf34 <unknown>
#18 0x7f8092894ac3 <unknown>

2024-02-06 09:20:19 ERROR Elements not present after 0.5 seconds on page: https://capital.com/trading/signup
2024-02-06 09:20:19 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 299, in element_is_visible
    return Wait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x560e921eed93 <unknown>
#1 0x560e91ed2337 <unknown>
#2 0x560e91f1dd60 <unknown>
#3 0x560e91f1de51 <unknown>
#4 0x560e91f61bc4 <unknown>
#5 0x560e91f4046d <unknown>
#6 0x560e91f5f12d <unknown>
#7 0x560e91f401e3 <unknown>
#8 0x560e91f10135 <unknown>
#9 0x560e91f1113e <unknown>
#10 0x560e921b2e4b <unknown>
#11 0x560e921b6dfa <unknown>
#12 0x560e9219f6d5 <unknown>
#13 0x560e921b7a6f <unknown>
#14 0x560e9218369f <unknown>
#15 0x560e921dc098 <unknown>
#16 0x560e921dc262 <unknown>
#17 0x560e921edf34 <unknown>
#18 0x7f8092894ac3 <unknown>

2024-02-06 09:20:23 ERROR Elements not present after 0.5 seconds on page: https://capital.com/trading/signup
2024-02-06 09:20:23 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 299, in element_is_visible
    return Wait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x560e921eed93 <unknown>
#1 0x560e91ed2337 <unknown>
#2 0x560e91f1dd60 <unknown>
#3 0x560e91f1de51 <unknown>
#4 0x560e91f61bc4 <unknown>
#5 0x560e91f4046d <unknown>
#6 0x560e91f5f12d <unknown>
#7 0x560e91f401e3 <unknown>
#8 0x560e91f10135 <unknown>
#9 0x560e91f1113e <unknown>
#10 0x560e921b2e4b <unknown>
#11 0x560e921b6dfa <unknown>
#12 0x560e9219f6d5 <unknown>
#13 0x560e921b7a6f <unknown>
#14 0x560e9218369f <unknown>
#15 0x560e921dc098 <unknown>
#16 0x560e921dc262 <unknown>
#17 0x560e921edf34 <unknown>
#18 0x7f8092894ac3 <unknown>

2024-02-06 09:20:26 ERROR Elements not present after 0.5 seconds on page: https://capital.com/trading/signup
2024-02-06 09:20:26 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 299, in element_is_visible
    return Wait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x560e921eed93 <unknown>
#1 0x560e91ed2337 <unknown>
#2 0x560e91f1dd60 <unknown>
#3 0x560e91f1de51 <unknown>
#4 0x560e91f61bc4 <unknown>
#5 0x560e91f4046d <unknown>
#6 0x560e91f5f12d <unknown>
#7 0x560e91f401e3 <unknown>
#8 0x560e91f10135 <unknown>
#9 0x560e91f1113e <unknown>
#10 0x560e921b2e4b <unknown>
#11 0x560e921b6dfa <unknown>
#12 0x560e9219f6d5 <unknown>
#13 0x560e921b7a6f <unknown>
#14 0x560e9218369f <unknown>
#15 0x560e921dc098 <unknown>
#16 0x560e921dc262 <unknown>
#17 0x560e921edf34 <unknown>
#18 0x7f8092894ac3 <unknown>

2024-02-06 09:20:28 ERROR Elements not present after 0.5 seconds on page: https://capital.com/trading/signup
2024-02-06 09:20:28 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 299, in element_is_visible
    return Wait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x560e921eed93 <unknown>
#1 0x560e91ed2337 <unknown>
#2 0x560e91f1dd60 <unknown>
#3 0x560e91f1de51 <unknown>
#4 0x560e91f61bc4 <unknown>
#5 0x560e91f4046d <unknown>
#6 0x560e91f5f12d <unknown>
#7 0x560e91f401e3 <unknown>
#8 0x560e91f10135 <unknown>
#9 0x560e91f1113e <unknown>
#10 0x560e921b2e4b <unknown>
#11 0x560e921b6dfa <unknown>
#12 0x560e9219f6d5 <unknown>
#13 0x560e921b7a6f <unknown>
#14 0x560e9218369f <unknown>
#15 0x560e921dc098 <unknown>
#16 0x560e921dc262 <unknown>
#17 0x560e921edf34 <unknown>
#18 0x7f8092894ac3 <unknown>