2024-02-06 10:21:46 ERROR Elements not present after 0.5 seconds on page: https://capital.com/de/waehrungshandel
2024-02-06 10:21:46 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 299, in element_is_visible
    return Wait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x56303bab8d93 <unknown>
#1 0x56303b79c337 <unknown>
#2 0x56303b7e7d60 <unknown>
#3 0x56303b7e7e51 <unknown>
#4 0x56303b82bbc4 <unknown>
#5 0x56303b80a46d <unknown>
#6 0x56303b82912d <unknown>
#7 0x56303b80a1e3 <unknown>
#8 0x56303b7da135 <unknown>
#9 0x56303b7db13e <unknown>
#10 0x56303ba7ce4b <unknown>
#11 0x56303ba80dfa <unknown>
#12 0x56303ba696d5 <unknown>
#13 0x56303ba81a6f <unknown>
#14 0x56303ba4d69f <unknown>
#15 0x56303baa6098 <unknown>
#16 0x56303baa6262 <unknown>
#17 0x56303bab7f34 <unknown>
#18 0x7f0c9d094ac3 <unknown>

2024-02-06 10:22:03 ERROR Elements not present after 0.5 seconds on page: https://capital.com/trading/platform/
2024-02-06 10:22:03 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 299, in element_is_visible
    return Wait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x56303bab8d93 <unknown>
#1 0x56303b79c337 <unknown>
#2 0x56303b7e7d60 <unknown>
#3 0x56303b7e7e51 <unknown>
#4 0x56303b82bbc4 <unknown>
#5 0x56303b80a46d <unknown>
#6 0x56303b82912d <unknown>
#7 0x56303b80a1e3 <unknown>
#8 0x56303b7da135 <unknown>
#9 0x56303b7db13e <unknown>
#10 0x56303ba7ce4b <unknown>
#11 0x56303ba80dfa <unknown>
#12 0x56303ba696d5 <unknown>
#13 0x56303ba81a6f <unknown>
#14 0x56303ba4d69f <unknown>
#15 0x56303baa6098 <unknown>
#16 0x56303baa6262 <unknown>
#17 0x56303bab7f34 <unknown>
#18 0x7f0c9d094ac3 <unknown>