2024-02-19 11:56:34 ERROR Elements not present after 0.5 seconds on page: https://capital.com/de/kryptowaehrung-handel
2024-02-19 11:56:34 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 84, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 301, in element_is_visible
    return Wait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x559f96e9b303 <unknown>
#1 0x559f96b802b7 <unknown>
#2 0x559f96bcbcc0 <unknown>
#3 0x559f96bcbdb1 <unknown>
#4 0x559f96c0fb44 <unknown>
#5 0x559f96bee3ad <unknown>
#6 0x559f96c0d07c <unknown>
#7 0x559f96bee123 <unknown>
#8 0x559f96bbe095 <unknown>
#9 0x559f96bbf09e <unknown>
#10 0x559f96e5f6ab <unknown>
#11 0x559f96e634ba <unknown>
#12 0x559f96e4bf85 <unknown>
#13 0x559f96e6412f <unknown>
#14 0x559f96e2fe6f <unknown>
#15 0x559f96e885f8 <unknown>
#16 0x559f96e887c2 <unknown>
#17 0x559f96e9a4a4 <unknown>
#18 0x7f5272094ac3 <unknown>

2024-02-19 11:56:53 ERROR Elements not present after 0.5 seconds on page: https://capital.com/trading/platform/charting/27342779713672388?side=buy&ids=93810675766468,15839732013552836,27342779713672388,2604592722433220,427748677997764,27045129890124996,3644116541985988,22595823031492,22855552501634244,21182778791108,16150730595456196,422839530378436,27041281599427780,426090820621508,888581716535497924,5983666832495812,21659404109698244,123763777688772,21680337780298948,12241936693896217,14659243072378052,1496662958757060,23381802046660,374675767075865,1679716659553719492,389523468997970,339804927579474,194965745456466,313532634450,1717986940242,1434519098706,5321464501586,508931114652423506,71150428247378,110522393449810,233693465629892,390880678663506,74865574958418,56959856301394,334595132249426
2024-02-19 11:56:53 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 84, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 301, in element_is_visible
    return Wait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x559f96e9b303 <unknown>
#1 0x559f96b802b7 <unknown>
#2 0x559f96bcbcc0 <unknown>
#3 0x559f96bcbdb1 <unknown>
#4 0x559f96c0fb44 <unknown>
#5 0x559f96bee3ad <unknown>
#6 0x559f96c0d07c <unknown>
#7 0x559f96bee123 <unknown>
#8 0x559f96bbe095 <unknown>
#9 0x559f96bbf09e <unknown>
#10 0x559f96e5f6ab <unknown>
#11 0x559f96e634ba <unknown>
#12 0x559f96e4bf85 <unknown>
#13 0x559f96e6412f <unknown>
#14 0x559f96e2fe6f <unknown>
#15 0x559f96e885f8 <unknown>
#16 0x559f96e887c2 <unknown>
#17 0x559f96e9a4a4 <unknown>
#18 0x7f5272094ac3 <unknown>