2024-03-30 06:30:59 ERROR Elements not present after 0.5 seconds on page: https://capital.com/asset-classes-margin
2024-03-30 06:30:59 ERROR Can't click element by locator ('css selector', '#s_overlay button.s_cancel')
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/Elements/LearnFirstTradeCFDBlockTryDemoButton.py", line 52, in element_click
    button_list[0].click()
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 94, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <a class="btn inBanner__btn rounded-lg ln-auto js-analyticsClick" href="/trading/signup" data-type="b_vert_new_style_879">...</a> is not clickable at point (952, 357). Other element would receive the click: <div class="onetrust-pc-dark-filter ot-fade-in" style="z-index:2147483645;"></div>
  (Session info: chrome=123.0.6312.58)
Stacktrace:
#0 0x55cf2981f8a3 <unknown>
#1 0x55cf295158c6 <unknown>
#2 0x55cf29567233 <unknown>
#3 0x55cf2956514e <unknown>
#4 0x55cf29562b27 <unknown>
#5 0x55cf29561ed3 <unknown>
#6 0x55cf29555507 <unknown>
#7 0x55cf295825a2 <unknown>
#8 0x55cf29554e98 <unknown>
#9 0x55cf2958276e <unknown>
#10 0x55cf295a0c19 <unknown>
#11 0x55cf29582343 <unknown>
#12 0x55cf29553593 <unknown>
#13 0x55cf29553f5e <unknown>
#14 0x55cf297e388b <unknown>
#15 0x55cf297e77e5 <unknown>
#16 0x55cf297d15b1 <unknown>
#17 0x55cf297e8372 <unknown>
#18 0x55cf297b68bf <unknown>
#19 0x55cf2980e768 <unknown>
#20 0x55cf2980e93b <unknown>
#21 0x55cf2981e9f4 <unknown>
#22 0x7f3821494ac3 <unknown>


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 85, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 346, in element_is_clickable
    return Wait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: Can't click element by locator ('css selector', '#s_overlay button.s_cancel')
Stacktrace:
#0 0x55cf2981f8a3 <unknown>
#1 0x55cf295158c6 <unknown>
#2 0x55cf29560618 <unknown>
#3 0x55cf295606d1 <unknown>
#4 0x55cf295a3744 <unknown>
#5 0x55cf295825cd <unknown>
#6 0x55cf295a0c19 <unknown>
#7 0x55cf29582343 <unknown>
#8 0x55cf29553593 <unknown>
#9 0x55cf29553f5e <unknown>
#10 0x55cf297e388b <unknown>
#11 0x55cf297e77e5 <unknown>
#12 0x55cf297d15b1 <unknown>
#13 0x55cf297e8372 <unknown>
#14 0x55cf297b68bf <unknown>
#15 0x55cf2980e768 <unknown>
#16 0x55cf2980e93b <unknown>
#17 0x55cf2981e9f4 <unknown>
#18 0x7f3821494ac3 <unknown>