2024-01-16 08:33:35 ERROR Elements not present after 0.5 seconds on page: https://capital.com/it/trade-amd
2024-01-16 08:33:35 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcom-CcJ6hTD8-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x55d666801f83 <unknown>
#1 0x55d6664bacf7 <unknown>
#2 0x55d66650a99e <unknown>
#3 0x55d66650aaa1 <unknown>
#4 0x55d666555d64 <unknown>
#5 0x55d6665340dd <unknown>
#6 0x55d666553006 <unknown>
#7 0x55d666533e53 <unknown>
#8 0x55d6664fbdd4 <unknown>
#9 0x55d6664fd1de <unknown>
#10 0x55d6667c6531 <unknown>
#11 0x55d6667ca455 <unknown>
#12 0x55d6667b2f55 <unknown>
#13 0x55d6667cb0ef <unknown>
#14 0x55d66679699f <unknown>
#15 0x55d6667ef008 <unknown>
#16 0x55d6667ef1d7 <unknown>
#17 0x55d666801124 <unknown>
#18 0x7f30a4694ac3 <unknown>

2024-01-16 08:33:47 ERROR Elements not present after 0.5 seconds on page: https://capital.com/trading/signup
2024-01-16 08:33:47 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcom-CcJ6hTD8-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x55d666801f83 <unknown>
#1 0x55d6664bacf7 <unknown>
#2 0x55d66650a99e <unknown>
#3 0x55d66650aaa1 <unknown>
#4 0x55d666555d64 <unknown>
#5 0x55d6665340dd <unknown>
#6 0x55d666553006 <unknown>
#7 0x55d666533e53 <unknown>
#8 0x55d6664fbdd4 <unknown>
#9 0x55d6664fd1de <unknown>
#10 0x55d6667c6531 <unknown>
#11 0x55d6667ca455 <unknown>
#12 0x55d6667b2f55 <unknown>
#13 0x55d6667cb0ef <unknown>
#14 0x55d66679699f <unknown>
#15 0x55d6667ef008 <unknown>
#16 0x55d6667ef1d7 <unknown>
#17 0x55d666801124 <unknown>
#18 0x7f30a4694ac3 <unknown>

2024-01-16 08:33:52 ERROR Elements not present after 0.5 seconds on page: https://capital.com/trading/signup
2024-01-16 08:33:52 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcom-CcJ6hTD8-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x55d666801f83 <unknown>
#1 0x55d6664bacf7 <unknown>
#2 0x55d66650a99e <unknown>
#3 0x55d66650aaa1 <unknown>
#4 0x55d666555d64 <unknown>
#5 0x55d6665340dd <unknown>
#6 0x55d666553006 <unknown>
#7 0x55d666533e53 <unknown>
#8 0x55d6664fbdd4 <unknown>
#9 0x55d6664fd1de <unknown>
#10 0x55d6667c6531 <unknown>
#11 0x55d6667ca455 <unknown>
#12 0x55d6667b2f55 <unknown>
#13 0x55d6667cb0ef <unknown>
#14 0x55d66679699f <unknown>
#15 0x55d6667ef008 <unknown>
#16 0x55d6667ef1d7 <unknown>
#17 0x55d666801124 <unknown>
#18 0x7f30a4694ac3 <unknown>

2024-01-16 08:33:58 ERROR Elements not present after 0.5 seconds on page: https://capital.com/trading/signup
2024-01-16 08:33:58 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcom-CcJ6hTD8-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x55d666801f83 <unknown>
#1 0x55d6664bacf7 <unknown>
#2 0x55d66650a99e <unknown>
#3 0x55d66650aaa1 <unknown>
#4 0x55d666555d64 <unknown>
#5 0x55d6665340dd <unknown>
#6 0x55d666553006 <unknown>
#7 0x55d666533e53 <unknown>
#8 0x55d6664fbdd4 <unknown>
#9 0x55d6664fd1de <unknown>
#10 0x55d6667c6531 <unknown>
#11 0x55d6667ca455 <unknown>
#12 0x55d6667b2f55 <unknown>
#13 0x55d6667cb0ef <unknown>
#14 0x55d66679699f <unknown>
#15 0x55d6667ef008 <unknown>
#16 0x55d6667ef1d7 <unknown>
#17 0x55d666801124 <unknown>
#18 0x7f30a4694ac3 <unknown>

2024-01-16 08:34:05 ERROR Elements not present after 0.5 seconds on page: https://capital.com/trading/signup
2024-01-16 08:34:05 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcom-CcJ6hTD8-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x55d666801f83 <unknown>
#1 0x55d6664bacf7 <unknown>
#2 0x55d66650a99e <unknown>
#3 0x55d66650aaa1 <unknown>
#4 0x55d666555d64 <unknown>
#5 0x55d6665340dd <unknown>
#6 0x55d666553006 <unknown>
#7 0x55d666533e53 <unknown>
#8 0x55d6664fbdd4 <unknown>
#9 0x55d6664fd1de <unknown>
#10 0x55d6667c6531 <unknown>
#11 0x55d6667ca455 <unknown>
#12 0x55d6667b2f55 <unknown>
#13 0x55d6667cb0ef <unknown>
#14 0x55d66679699f <unknown>
#15 0x55d6667ef008 <unknown>
#16 0x55d6667ef1d7 <unknown>
#17 0x55d666801124 <unknown>
#18 0x7f30a4694ac3 <unknown>