2024-02-22 08:27:57 ERROR Elements not present after 0.5 seconds on page: https://capital.com/pl/handlovac-palladem
2024-02-22 08:27:57 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 84, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 301, in element_is_visible
    return Wait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5632b539c303 <unknown>
#1 0x5632b50812b7 <unknown>
#2 0x5632b50cccc0 <unknown>
#3 0x5632b50ccdb1 <unknown>
#4 0x5632b5110b44 <unknown>
#5 0x5632b50ef3ad <unknown>
#6 0x5632b510e07c <unknown>
#7 0x5632b50ef123 <unknown>
#8 0x5632b50bf095 <unknown>
#9 0x5632b50c009e <unknown>
#10 0x5632b53606ab <unknown>
#11 0x5632b53644ba <unknown>
#12 0x5632b534cf85 <unknown>
#13 0x5632b536512f <unknown>
#14 0x5632b5330e6f <unknown>
#15 0x5632b53895f8 <unknown>
#16 0x5632b53897c2 <unknown>
#17 0x5632b539b4a4 <unknown>
#18 0x7f0a6e094ac3 <unknown>

2024-02-22 08:29:15 ERROR Elements not present after 0.5 seconds on page: https://capital.com/trading/platform/
2024-02-22 08:29:15 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 84, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 301, in element_is_visible
    return Wait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5632b539c303 <unknown>
#1 0x5632b50812b7 <unknown>
#2 0x5632b50cccc0 <unknown>
#3 0x5632b50ccdb1 <unknown>
#4 0x5632b5110b44 <unknown>
#5 0x5632b50ef3ad <unknown>
#6 0x5632b510e07c <unknown>
#7 0x5632b50ef123 <unknown>
#8 0x5632b50bf095 <unknown>
#9 0x5632b50c009e <unknown>
#10 0x5632b53606ab <unknown>
#11 0x5632b53644ba <unknown>
#12 0x5632b534cf85 <unknown>
#13 0x5632b536512f <unknown>
#14 0x5632b5330e6f <unknown>
#15 0x5632b53895f8 <unknown>
#16 0x5632b53897c2 <unknown>
#17 0x5632b539b4a4 <unknown>
#18 0x7f0a6e094ac3 <unknown>