2023-12-14 22:47:13 ERROR Unable to initialize WebDriver
2023-12-14 22:47:13 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 394, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcom-CcJ6hTD8-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5636587f0d33 <unknown>
#1 0x5636584adf87 <unknown>
#2 0x5636584fdc0e <unknown>
#3 0x5636584fdd11 <unknown>
#4 0x563658549004 <unknown>
#5 0x56365852736d <unknown>
#6 0x563658546297 <unknown>
#7 0x5636585270e3 <unknown>
#8 0x5636584ef044 <unknown>
#9 0x5636584f044e <unknown>
#10 0x5636587b5861 <unknown>
#11 0x5636587b9785 <unknown>
#12 0x5636587a3285 <unknown>
#13 0x5636587ba41f <unknown>
#14 0x56365878720f <unknown>
#15 0x5636587de028 <unknown>
#16 0x5636587de1f7 <unknown>
#17 0x5636587efed4 <unknown>
#18 0x7f1218894ac3 <unknown>

2023-12-14 22:47:17 ERROR Unable to initialize WebDriver
2023-12-14 22:47:17 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 394, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcom-CcJ6hTD8-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5636587f0d33 <unknown>
#1 0x5636584adf87 <unknown>
#2 0x5636584fdc0e <unknown>
#3 0x5636584fdd11 <unknown>
#4 0x563658549004 <unknown>
#5 0x56365852736d <unknown>
#6 0x563658546297 <unknown>
#7 0x5636585270e3 <unknown>
#8 0x5636584ef044 <unknown>
#9 0x5636584f044e <unknown>
#10 0x5636587b5861 <unknown>
#11 0x5636587b9785 <unknown>
#12 0x5636587a3285 <unknown>
#13 0x5636587ba41f <unknown>
#14 0x56365878720f <unknown>
#15 0x5636587de028 <unknown>
#16 0x5636587de1f7 <unknown>
#17 0x5636587efed4 <unknown>
#18 0x7f1218894ac3 <unknown>

2023-12-14 22:47:22 ERROR Unable to initialize WebDriver
2023-12-14 22:47:22 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 394, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcom-CcJ6hTD8-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5636587f0d33 <unknown>
#1 0x5636584adf87 <unknown>
#2 0x5636584fdc0e <unknown>
#3 0x5636584fdd11 <unknown>
#4 0x563658549004 <unknown>
#5 0x56365852736d <unknown>
#6 0x563658546297 <unknown>
#7 0x5636585270e3 <unknown>
#8 0x5636584ef044 <unknown>
#9 0x5636584f044e <unknown>
#10 0x5636587b5861 <unknown>
#11 0x5636587b9785 <unknown>
#12 0x5636587a3285 <unknown>
#13 0x5636587ba41f <unknown>
#14 0x56365878720f <unknown>
#15 0x5636587de028 <unknown>
#16 0x5636587de1f7 <unknown>
#17 0x5636587efed4 <unknown>
#18 0x7f1218894ac3 <unknown>

2023-12-14 22:47:28 ERROR Unable to initialize WebDriver
2023-12-14 22:47:28 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 394, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcom-CcJ6hTD8-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5636587f0d33 <unknown>
#1 0x5636584adf87 <unknown>
#2 0x5636584fdc0e <unknown>
#3 0x5636584fdd11 <unknown>
#4 0x563658549004 <unknown>
#5 0x56365852736d <unknown>
#6 0x563658546297 <unknown>
#7 0x5636585270e3 <unknown>
#8 0x5636584ef044 <unknown>
#9 0x5636584f044e <unknown>
#10 0x5636587b5861 <unknown>
#11 0x5636587b9785 <unknown>
#12 0x5636587a3285 <unknown>
#13 0x5636587ba41f <unknown>
#14 0x56365878720f <unknown>
#15 0x5636587de028 <unknown>
#16 0x5636587de1f7 <unknown>
#17 0x5636587efed4 <unknown>
#18 0x7f1218894ac3 <unknown>