2024-04-21 04:36:57 ERROR Elements not present after 0.5 seconds on page: https://capital.com/trading/platform/
2024-04-21 04:36:57 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 85, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 304, in element_is_visible
    return Wait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x564dd06b3863 <unknown>
#1 0x564dd03a98c6 <unknown>
#2 0x564dd03f4618 <unknown>
#3 0x564dd03f46d1 <unknown>
#4 0x564dd0437744 <unknown>
#5 0x564dd04165cd <unknown>
#6 0x564dd0434c19 <unknown>
#7 0x564dd0416343 <unknown>
#8 0x564dd03e7593 <unknown>
#9 0x564dd03e7f5e <unknown>
#10 0x564dd067784b <unknown>
#11 0x564dd067b7a5 <unknown>
#12 0x564dd0665571 <unknown>
#13 0x564dd067c332 <unknown>
#14 0x564dd064a87f <unknown>
#15 0x564dd06a2728 <unknown>
#16 0x564dd06a28fb <unknown>
#17 0x564dd06b29b4 <unknown>
#18 0x7f357c294ac3 <unknown>

2024-04-21 04:37:00 ERROR Elements not present after 0.5 seconds on page: https://capital.com/trading/platform/
2024-04-21 04:37:00 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 85, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 304, in element_is_visible
    return Wait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x564dd06b3863 <unknown>
#1 0x564dd03a98c6 <unknown>
#2 0x564dd03f4618 <unknown>
#3 0x564dd03f46d1 <unknown>
#4 0x564dd0437744 <unknown>
#5 0x564dd04165cd <unknown>
#6 0x564dd0434c19 <unknown>
#7 0x564dd0416343 <unknown>
#8 0x564dd03e7593 <unknown>
#9 0x564dd03e7f5e <unknown>
#10 0x564dd067784b <unknown>
#11 0x564dd067b7a5 <unknown>
#12 0x564dd0665571 <unknown>
#13 0x564dd067c332 <unknown>
#14 0x564dd064a87f <unknown>
#15 0x564dd06a2728 <unknown>
#16 0x564dd06a28fb <unknown>
#17 0x564dd06b29b4 <unknown>
#18 0x7f357c294ac3 <unknown>

2024-04-21 04:37:04 ERROR Elements not present after 0.5 seconds on page: https://capital.com/trading/platform/
2024-04-21 04:37:04 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 85, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 304, in element_is_visible
    return Wait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x564dd06b3863 <unknown>
#1 0x564dd03a98c6 <unknown>
#2 0x564dd03f4618 <unknown>
#3 0x564dd03f46d1 <unknown>
#4 0x564dd0437744 <unknown>
#5 0x564dd04165cd <unknown>
#6 0x564dd0434c19 <unknown>
#7 0x564dd0416343 <unknown>
#8 0x564dd03e7593 <unknown>
#9 0x564dd03e7f5e <unknown>
#10 0x564dd067784b <unknown>
#11 0x564dd067b7a5 <unknown>
#12 0x564dd0665571 <unknown>
#13 0x564dd067c332 <unknown>
#14 0x564dd064a87f <unknown>
#15 0x564dd06a2728 <unknown>
#16 0x564dd06a28fb <unknown>
#17 0x564dd06b29b4 <unknown>
#18 0x7f357c294ac3 <unknown>

2024-04-21 04:37:07 ERROR Elements not present after 0.5 seconds on page: https://capital.com/trading/platform/
2024-04-21 04:37:07 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 85, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 304, in element_is_visible
    return Wait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x564dd06b3863 <unknown>
#1 0x564dd03a98c6 <unknown>
#2 0x564dd03f4618 <unknown>
#3 0x564dd03f46d1 <unknown>
#4 0x564dd0437744 <unknown>
#5 0x564dd04165cd <unknown>
#6 0x564dd0434c19 <unknown>
#7 0x564dd0416343 <unknown>
#8 0x564dd03e7593 <unknown>
#9 0x564dd03e7f5e <unknown>
#10 0x564dd067784b <unknown>
#11 0x564dd067b7a5 <unknown>
#12 0x564dd0665571 <unknown>
#13 0x564dd067c332 <unknown>
#14 0x564dd064a87f <unknown>
#15 0x564dd06a2728 <unknown>
#16 0x564dd06a28fb <unknown>
#17 0x564dd06b29b4 <unknown>
#18 0x7f357c294ac3 <unknown>

2024-04-21 04:37:10 ERROR Elements not present after 0.5 seconds on page: https://capital.com/trading/platform/
2024-04-21 04:37:10 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 85, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 304, in element_is_visible
    return Wait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x564dd06b3863 <unknown>
#1 0x564dd03a98c6 <unknown>
#2 0x564dd03f4618 <unknown>
#3 0x564dd03f46d1 <unknown>
#4 0x564dd0437744 <unknown>
#5 0x564dd04165cd <unknown>
#6 0x564dd0434c19 <unknown>
#7 0x564dd0416343 <unknown>
#8 0x564dd03e7593 <unknown>
#9 0x564dd03e7f5e <unknown>
#10 0x564dd067784b <unknown>
#11 0x564dd067b7a5 <unknown>
#12 0x564dd0665571 <unknown>
#13 0x564dd067c332 <unknown>
#14 0x564dd064a87f <unknown>
#15 0x564dd06a2728 <unknown>
#16 0x564dd06a28fb <unknown>
#17 0x564dd06b29b4 <unknown>
#18 0x7f357c294ac3 <unknown>