2024-01-26 06:22:23 ERROR Elements not present after 0.5 seconds on page: https://capital.com/cfd-trading-strategy
2024-01-26 06:22:23 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5631c8f7af83 <unknown>
#1 0x5631c8c33cf7 <unknown>
#2 0x5631c8c8399e <unknown>
#3 0x5631c8c83aa1 <unknown>
#4 0x5631c8cced64 <unknown>
#5 0x5631c8cad0dd <unknown>
#6 0x5631c8ccc006 <unknown>
#7 0x5631c8cace53 <unknown>
#8 0x5631c8c74dd4 <unknown>
#9 0x5631c8c761de <unknown>
#10 0x5631c8f3f531 <unknown>
#11 0x5631c8f43455 <unknown>
#12 0x5631c8f2bf55 <unknown>
#13 0x5631c8f440ef <unknown>
#14 0x5631c8f0f99f <unknown>
#15 0x5631c8f68008 <unknown>
#16 0x5631c8f681d7 <unknown>
#17 0x5631c8f7a124 <unknown>
#18 0x7f99c4c94ac3 <unknown>

2024-01-26 06:22:29 ERROR Elements not present after 0.5 seconds on page: https://capital.com/cfd-trading-strategy
2024-01-26 06:22:29 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 293, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5631c8f7af83 <unknown>
#1 0x5631c8c33cf7 <unknown>
#2 0x5631c8c8399e <unknown>
#3 0x5631c8c83aa1 <unknown>
#4 0x5631c8cced64 <unknown>
#5 0x5631c8cad0dd <unknown>
#6 0x5631c8ccc006 <unknown>
#7 0x5631c8cace53 <unknown>
#8 0x5631c8c74dd4 <unknown>
#9 0x5631c8c761de <unknown>
#10 0x5631c8f3f531 <unknown>
#11 0x5631c8f43455 <unknown>
#12 0x5631c8f2bf55 <unknown>
#13 0x5631c8f440ef <unknown>
#14 0x5631c8f0f99f <unknown>
#15 0x5631c8f68008 <unknown>
#16 0x5631c8f681d7 <unknown>
#17 0x5631c8f7a124 <unknown>
#18 0x7f99c4c94ac3 <unknown>