2023-12-13 23:55:22 ERROR Unable to initialize WebDriver
2023-12-13 23:55:22 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 394, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcom-CcJ6hTD8-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5612cc8d35e3 <unknown>
#1 0x5612cc5960b7 <unknown>
#2 0x5612cc5e3f53 <unknown>
#3 0x5612cc5e4051 <unknown>
#4 0x5612cc6299c4 <unknown>
#5 0x5612cc60af1d <unknown>
#6 0x5612cc626b3d <unknown>
#7 0x5612cc60acc3 <unknown>
#8 0x5612cc5d60e4 <unknown>
#9 0x5612cc5d70ae <unknown>
#10 0x5612cc899ce1 <unknown>
#11 0x5612cc89db7e <unknown>
#12 0x5612cc8874b5 <unknown>
#13 0x5612cc89e7d6 <unknown>
#14 0x5612cc86adbf <unknown>
#15 0x5612cc8c1748 <unknown>
#16 0x5612cc8c1917 <unknown>
#17 0x5612cc8d2773 <unknown>
#18 0x7f48b4e94ac3 <unknown>

2023-12-13 23:55:29 ERROR Unable to initialize WebDriver
2023-12-13 23:55:29 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 394, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcom-CcJ6hTD8-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5612cc8d35e3 <unknown>
#1 0x5612cc5960b7 <unknown>
#2 0x5612cc5e3f53 <unknown>
#3 0x5612cc5e4051 <unknown>
#4 0x5612cc6299c4 <unknown>
#5 0x5612cc60af1d <unknown>
#6 0x5612cc626b3d <unknown>
#7 0x5612cc60acc3 <unknown>
#8 0x5612cc5d60e4 <unknown>
#9 0x5612cc5d70ae <unknown>
#10 0x5612cc899ce1 <unknown>
#11 0x5612cc89db7e <unknown>
#12 0x5612cc8874b5 <unknown>
#13 0x5612cc89e7d6 <unknown>
#14 0x5612cc86adbf <unknown>
#15 0x5612cc8c1748 <unknown>
#16 0x5612cc8c1917 <unknown>
#17 0x5612cc8d2773 <unknown>
#18 0x7f48b4e94ac3 <unknown>

2023-12-13 23:55:36 ERROR Unable to initialize WebDriver
2023-12-13 23:55:36 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 394, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcom-CcJ6hTD8-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5612cc8d35e3 <unknown>
#1 0x5612cc5960b7 <unknown>
#2 0x5612cc5e3f53 <unknown>
#3 0x5612cc5e4051 <unknown>
#4 0x5612cc6299c4 <unknown>
#5 0x5612cc60af1d <unknown>
#6 0x5612cc626b3d <unknown>
#7 0x5612cc60acc3 <unknown>
#8 0x5612cc5d60e4 <unknown>
#9 0x5612cc5d70ae <unknown>
#10 0x5612cc899ce1 <unknown>
#11 0x5612cc89db7e <unknown>
#12 0x5612cc8874b5 <unknown>
#13 0x5612cc89e7d6 <unknown>
#14 0x5612cc86adbf <unknown>
#15 0x5612cc8c1748 <unknown>
#16 0x5612cc8c1917 <unknown>
#17 0x5612cc8d2773 <unknown>
#18 0x7f48b4e94ac3 <unknown>

2023-12-13 23:55:42 ERROR Unable to initialize WebDriver
2023-12-13 23:55:42 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 394, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcom-CcJ6hTD8-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5612cc8d35e3 <unknown>
#1 0x5612cc5960b7 <unknown>
#2 0x5612cc5e3f53 <unknown>
#3 0x5612cc5e4051 <unknown>
#4 0x5612cc6299c4 <unknown>
#5 0x5612cc60af1d <unknown>
#6 0x5612cc626b3d <unknown>
#7 0x5612cc60acc3 <unknown>
#8 0x5612cc5d60e4 <unknown>
#9 0x5612cc5d70ae <unknown>
#10 0x5612cc899ce1 <unknown>
#11 0x5612cc89db7e <unknown>
#12 0x5612cc8874b5 <unknown>
#13 0x5612cc89e7d6 <unknown>
#14 0x5612cc86adbf <unknown>
#15 0x5612cc8c1748 <unknown>
#16 0x5612cc8c1917 <unknown>
#17 0x5612cc8d2773 <unknown>
#18 0x7f48b4e94ac3 <unknown>

2023-12-13 23:55:49 ERROR Unable to initialize WebDriver
2023-12-13 23:55:49 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 394, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcom-CcJ6hTD8-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5612cc8d35e3 <unknown>
#1 0x5612cc5960b7 <unknown>
#2 0x5612cc5e3f53 <unknown>
#3 0x5612cc5e4051 <unknown>
#4 0x5612cc6299c4 <unknown>
#5 0x5612cc60af1d <unknown>
#6 0x5612cc626b3d <unknown>
#7 0x5612cc60acc3 <unknown>
#8 0x5612cc5d60e4 <unknown>
#9 0x5612cc5d70ae <unknown>
#10 0x5612cc899ce1 <unknown>
#11 0x5612cc89db7e <unknown>
#12 0x5612cc8874b5 <unknown>
#13 0x5612cc89e7d6 <unknown>
#14 0x5612cc86adbf <unknown>
#15 0x5612cc8c1748 <unknown>
#16 0x5612cc8c1917 <unknown>
#17 0x5612cc8d2773 <unknown>
#18 0x7f48b4e94ac3 <unknown>

2023-12-13 23:55:55 ERROR Unable to initialize WebDriver
2023-12-13 23:55:55 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 394, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcom-CcJ6hTD8-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5612cc8d35e3 <unknown>
#1 0x5612cc5960b7 <unknown>
#2 0x5612cc5e3f53 <unknown>
#3 0x5612cc5e4051 <unknown>
#4 0x5612cc6299c4 <unknown>
#5 0x5612cc60af1d <unknown>
#6 0x5612cc626b3d <unknown>
#7 0x5612cc60acc3 <unknown>
#8 0x5612cc5d60e4 <unknown>
#9 0x5612cc5d70ae <unknown>
#10 0x5612cc899ce1 <unknown>
#11 0x5612cc89db7e <unknown>
#12 0x5612cc8874b5 <unknown>
#13 0x5612cc89e7d6 <unknown>
#14 0x5612cc86adbf <unknown>
#15 0x5612cc8c1748 <unknown>
#16 0x5612cc8c1917 <unknown>
#17 0x5612cc8d2773 <unknown>
#18 0x7f48b4e94ac3 <unknown>

2023-12-13 23:56:02 ERROR Unable to initialize WebDriver
2023-12-13 23:56:02 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 394, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcom-CcJ6hTD8-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5612cc8d35e3 <unknown>
#1 0x5612cc5960b7 <unknown>
#2 0x5612cc5e3f53 <unknown>
#3 0x5612cc5e4051 <unknown>
#4 0x5612cc6299c4 <unknown>
#5 0x5612cc60af1d <unknown>
#6 0x5612cc626b3d <unknown>
#7 0x5612cc60acc3 <unknown>
#8 0x5612cc5d60e4 <unknown>
#9 0x5612cc5d70ae <unknown>
#10 0x5612cc899ce1 <unknown>
#11 0x5612cc89db7e <unknown>
#12 0x5612cc8874b5 <unknown>
#13 0x5612cc89e7d6 <unknown>
#14 0x5612cc86adbf <unknown>
#15 0x5612cc8c1748 <unknown>
#16 0x5612cc8c1917 <unknown>
#17 0x5612cc8d2773 <unknown>
#18 0x7f48b4e94ac3 <unknown>

2023-12-13 23:56:08 ERROR Unable to initialize WebDriver
2023-12-13 23:56:08 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 394, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcom-CcJ6hTD8-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5612cc8d35e3 <unknown>
#1 0x5612cc5960b7 <unknown>
#2 0x5612cc5e3f53 <unknown>
#3 0x5612cc5e4051 <unknown>
#4 0x5612cc6299c4 <unknown>
#5 0x5612cc60af1d <unknown>
#6 0x5612cc626b3d <unknown>
#7 0x5612cc60acc3 <unknown>
#8 0x5612cc5d60e4 <unknown>
#9 0x5612cc5d70ae <unknown>
#10 0x5612cc899ce1 <unknown>
#11 0x5612cc89db7e <unknown>
#12 0x5612cc8874b5 <unknown>
#13 0x5612cc89e7d6 <unknown>
#14 0x5612cc86adbf <unknown>
#15 0x5612cc8c1748 <unknown>
#16 0x5612cc8c1917 <unknown>
#17 0x5612cc8d2773 <unknown>
#18 0x7f48b4e94ac3 <unknown>

2023-12-13 23:56:15 ERROR Unable to initialize WebDriver
2023-12-13 23:56:15 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 394, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcom-CcJ6hTD8-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5612cc8d35e3 <unknown>
#1 0x5612cc5960b7 <unknown>
#2 0x5612cc5e3f53 <unknown>
#3 0x5612cc5e4051 <unknown>
#4 0x5612cc6299c4 <unknown>
#5 0x5612cc60af1d <unknown>
#6 0x5612cc626b3d <unknown>
#7 0x5612cc60acc3 <unknown>
#8 0x5612cc5d60e4 <unknown>
#9 0x5612cc5d70ae <unknown>
#10 0x5612cc899ce1 <unknown>
#11 0x5612cc89db7e <unknown>
#12 0x5612cc8874b5 <unknown>
#13 0x5612cc89e7d6 <unknown>
#14 0x5612cc86adbf <unknown>
#15 0x5612cc8c1748 <unknown>
#16 0x5612cc8c1917 <unknown>
#17 0x5612cc8d2773 <unknown>
#18 0x7f48b4e94ac3 <unknown>

2023-12-13 23:56:21 ERROR Unable to initialize WebDriver
2023-12-13 23:56:21 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 394, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcom-CcJ6hTD8-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5612cc8d35e3 <unknown>
#1 0x5612cc5960b7 <unknown>
#2 0x5612cc5e3f53 <unknown>
#3 0x5612cc5e4051 <unknown>
#4 0x5612cc6299c4 <unknown>
#5 0x5612cc60af1d <unknown>
#6 0x5612cc626b3d <unknown>
#7 0x5612cc60acc3 <unknown>
#8 0x5612cc5d60e4 <unknown>
#9 0x5612cc5d70ae <unknown>
#10 0x5612cc899ce1 <unknown>
#11 0x5612cc89db7e <unknown>
#12 0x5612cc8874b5 <unknown>
#13 0x5612cc89e7d6 <unknown>
#14 0x5612cc86adbf <unknown>
#15 0x5612cc8c1748 <unknown>
#16 0x5612cc8c1917 <unknown>
#17 0x5612cc8d2773 <unknown>
#18 0x7f48b4e94ac3 <unknown>

2023-12-13 23:56:28 ERROR Unable to initialize WebDriver
2023-12-13 23:56:28 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 394, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcom-CcJ6hTD8-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5612cc8d35e3 <unknown>
#1 0x5612cc5960b7 <unknown>
#2 0x5612cc5e3f53 <unknown>
#3 0x5612cc5e4051 <unknown>
#4 0x5612cc6299c4 <unknown>
#5 0x5612cc60af1d <unknown>
#6 0x5612cc626b3d <unknown>
#7 0x5612cc60acc3 <unknown>
#8 0x5612cc5d60e4 <unknown>
#9 0x5612cc5d70ae <unknown>
#10 0x5612cc899ce1 <unknown>
#11 0x5612cc89db7e <unknown>
#12 0x5612cc8874b5 <unknown>
#13 0x5612cc89e7d6 <unknown>
#14 0x5612cc86adbf <unknown>
#15 0x5612cc8c1748 <unknown>
#16 0x5612cc8c1917 <unknown>
#17 0x5612cc8d2773 <unknown>
#18 0x7f48b4e94ac3 <unknown>

2023-12-13 23:56:34 ERROR Unable to initialize WebDriver
2023-12-13 23:56:34 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 394, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcom-CcJ6hTD8-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5612cc8d35e3 <unknown>
#1 0x5612cc5960b7 <unknown>
#2 0x5612cc5e3f53 <unknown>
#3 0x5612cc5e4051 <unknown>
#4 0x5612cc6299c4 <unknown>
#5 0x5612cc60af1d <unknown>
#6 0x5612cc626b3d <unknown>
#7 0x5612cc60acc3 <unknown>
#8 0x5612cc5d60e4 <unknown>
#9 0x5612cc5d70ae <unknown>
#10 0x5612cc899ce1 <unknown>
#11 0x5612cc89db7e <unknown>
#12 0x5612cc8874b5 <unknown>
#13 0x5612cc89e7d6 <unknown>
#14 0x5612cc86adbf <unknown>
#15 0x5612cc8c1748 <unknown>
#16 0x5612cc8c1917 <unknown>
#17 0x5612cc8d2773 <unknown>
#18 0x7f48b4e94ac3 <unknown>

2023-12-13 23:56:41 ERROR Unable to initialize WebDriver
2023-12-13 23:56:41 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 394, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcom-CcJ6hTD8-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5612cc8d35e3 <unknown>
#1 0x5612cc5960b7 <unknown>
#2 0x5612cc5e3f53 <unknown>
#3 0x5612cc5e4051 <unknown>
#4 0x5612cc6299c4 <unknown>
#5 0x5612cc60af1d <unknown>
#6 0x5612cc626b3d <unknown>
#7 0x5612cc60acc3 <unknown>
#8 0x5612cc5d60e4 <unknown>
#9 0x5612cc5d70ae <unknown>
#10 0x5612cc899ce1 <unknown>
#11 0x5612cc89db7e <unknown>
#12 0x5612cc8874b5 <unknown>
#13 0x5612cc89e7d6 <unknown>
#14 0x5612cc86adbf <unknown>
#15 0x5612cc8c1748 <unknown>
#16 0x5612cc8c1917 <unknown>
#17 0x5612cc8d2773 <unknown>
#18 0x7f48b4e94ac3 <unknown>

2023-12-13 23:56:47 ERROR Unable to initialize WebDriver
2023-12-13 23:56:47 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 394, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcom-CcJ6hTD8-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5612cc8d35e3 <unknown>
#1 0x5612cc5960b7 <unknown>
#2 0x5612cc5e3f53 <unknown>
#3 0x5612cc5e4051 <unknown>
#4 0x5612cc6299c4 <unknown>
#5 0x5612cc60af1d <unknown>
#6 0x5612cc626b3d <unknown>
#7 0x5612cc60acc3 <unknown>
#8 0x5612cc5d60e4 <unknown>
#9 0x5612cc5d70ae <unknown>
#10 0x5612cc899ce1 <unknown>
#11 0x5612cc89db7e <unknown>
#12 0x5612cc8874b5 <unknown>
#13 0x5612cc89e7d6 <unknown>
#14 0x5612cc86adbf <unknown>
#15 0x5612cc8c1748 <unknown>
#16 0x5612cc8c1917 <unknown>
#17 0x5612cc8d2773 <unknown>
#18 0x7f48b4e94ac3 <unknown>

2023-12-13 23:56:54 ERROR Unable to initialize WebDriver
2023-12-13 23:56:54 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 394, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcom-CcJ6hTD8-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5612cc8d35e3 <unknown>
#1 0x5612cc5960b7 <unknown>
#2 0x5612cc5e3f53 <unknown>
#3 0x5612cc5e4051 <unknown>
#4 0x5612cc6299c4 <unknown>
#5 0x5612cc60af1d <unknown>
#6 0x5612cc626b3d <unknown>
#7 0x5612cc60acc3 <unknown>
#8 0x5612cc5d60e4 <unknown>
#9 0x5612cc5d70ae <unknown>
#10 0x5612cc899ce1 <unknown>
#11 0x5612cc89db7e <unknown>
#12 0x5612cc8874b5 <unknown>
#13 0x5612cc89e7d6 <unknown>
#14 0x5612cc86adbf <unknown>
#15 0x5612cc8c1748 <unknown>
#16 0x5612cc8c1917 <unknown>
#17 0x5612cc8d2773 <unknown>
#18 0x7f48b4e94ac3 <unknown>

2023-12-13 23:57:01 ERROR Unable to initialize WebDriver
2023-12-13 23:57:01 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 394, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcom-CcJ6hTD8-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5612cc8d35e3 <unknown>
#1 0x5612cc5960b7 <unknown>
#2 0x5612cc5e3f53 <unknown>
#3 0x5612cc5e4051 <unknown>
#4 0x5612cc6299c4 <unknown>
#5 0x5612cc60af1d <unknown>
#6 0x5612cc626b3d <unknown>
#7 0x5612cc60acc3 <unknown>
#8 0x5612cc5d60e4 <unknown>
#9 0x5612cc5d70ae <unknown>
#10 0x5612cc899ce1 <unknown>
#11 0x5612cc89db7e <unknown>
#12 0x5612cc8874b5 <unknown>
#13 0x5612cc89e7d6 <unknown>
#14 0x5612cc86adbf <unknown>
#15 0x5612cc8c1748 <unknown>
#16 0x5612cc8c1917 <unknown>
#17 0x5612cc8d2773 <unknown>
#18 0x7f48b4e94ac3 <unknown>

2023-12-13 23:57:07 ERROR Unable to initialize WebDriver
2023-12-13 23:57:07 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 394, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcom-CcJ6hTD8-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5612cc8d35e3 <unknown>
#1 0x5612cc5960b7 <unknown>
#2 0x5612cc5e3f53 <unknown>
#3 0x5612cc5e4051 <unknown>
#4 0x5612cc6299c4 <unknown>
#5 0x5612cc60af1d <unknown>
#6 0x5612cc626b3d <unknown>
#7 0x5612cc60acc3 <unknown>
#8 0x5612cc5d60e4 <unknown>
#9 0x5612cc5d70ae <unknown>
#10 0x5612cc899ce1 <unknown>
#11 0x5612cc89db7e <unknown>
#12 0x5612cc8874b5 <unknown>
#13 0x5612cc89e7d6 <unknown>
#14 0x5612cc86adbf <unknown>
#15 0x5612cc8c1748 <unknown>
#16 0x5612cc8c1917 <unknown>
#17 0x5612cc8d2773 <unknown>
#18 0x7f48b4e94ac3 <unknown>

2023-12-13 23:57:14 ERROR Unable to initialize WebDriver
2023-12-13 23:57:14 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 394, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcom-CcJ6hTD8-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5612cc8d35e3 <unknown>
#1 0x5612cc5960b7 <unknown>
#2 0x5612cc5e3f53 <unknown>
#3 0x5612cc5e4051 <unknown>
#4 0x5612cc6299c4 <unknown>
#5 0x5612cc60af1d <unknown>
#6 0x5612cc626b3d <unknown>
#7 0x5612cc60acc3 <unknown>
#8 0x5612cc5d60e4 <unknown>
#9 0x5612cc5d70ae <unknown>
#10 0x5612cc899ce1 <unknown>
#11 0x5612cc89db7e <unknown>
#12 0x5612cc8874b5 <unknown>
#13 0x5612cc89e7d6 <unknown>
#14 0x5612cc86adbf <unknown>
#15 0x5612cc8c1748 <unknown>
#16 0x5612cc8c1917 <unknown>
#17 0x5612cc8d2773 <unknown>
#18 0x7f48b4e94ac3 <unknown>

2023-12-13 23:57:21 ERROR Unable to initialize WebDriver
2023-12-13 23:57:21 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 394, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcom-CcJ6hTD8-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5612cc8d35e3 <unknown>
#1 0x5612cc5960b7 <unknown>
#2 0x5612cc5e3f53 <unknown>
#3 0x5612cc5e4051 <unknown>
#4 0x5612cc6299c4 <unknown>
#5 0x5612cc60af1d <unknown>
#6 0x5612cc626b3d <unknown>
#7 0x5612cc60acc3 <unknown>
#8 0x5612cc5d60e4 <unknown>
#9 0x5612cc5d70ae <unknown>
#10 0x5612cc899ce1 <unknown>
#11 0x5612cc89db7e <unknown>
#12 0x5612cc8874b5 <unknown>
#13 0x5612cc89e7d6 <unknown>
#14 0x5612cc86adbf <unknown>
#15 0x5612cc8c1748 <unknown>
#16 0x5612cc8c1917 <unknown>
#17 0x5612cc8d2773 <unknown>
#18 0x7f48b4e94ac3 <unknown>

2023-12-13 23:57:27 ERROR Unable to initialize WebDriver
2023-12-13 23:57:27 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 394, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcom-CcJ6hTD8-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5612cc8d35e3 <unknown>
#1 0x5612cc5960b7 <unknown>
#2 0x5612cc5e3f53 <unknown>
#3 0x5612cc5e4051 <unknown>
#4 0x5612cc6299c4 <unknown>
#5 0x5612cc60af1d <unknown>
#6 0x5612cc626b3d <unknown>
#7 0x5612cc60acc3 <unknown>
#8 0x5612cc5d60e4 <unknown>
#9 0x5612cc5d70ae <unknown>
#10 0x5612cc899ce1 <unknown>
#11 0x5612cc89db7e <unknown>
#12 0x5612cc8874b5 <unknown>
#13 0x5612cc89e7d6 <unknown>
#14 0x5612cc86adbf <unknown>
#15 0x5612cc8c1748 <unknown>
#16 0x5612cc8c1917 <unknown>
#17 0x5612cc8d2773 <unknown>
#18 0x7f48b4e94ac3 <unknown>

2023-12-13 23:57:34 ERROR Unable to initialize WebDriver
2023-12-13 23:57:34 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 394, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcom-CcJ6hTD8-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5612cc8d35e3 <unknown>
#1 0x5612cc5960b7 <unknown>
#2 0x5612cc5e3f53 <unknown>
#3 0x5612cc5e4051 <unknown>
#4 0x5612cc6299c4 <unknown>
#5 0x5612cc60af1d <unknown>
#6 0x5612cc626b3d <unknown>
#7 0x5612cc60acc3 <unknown>
#8 0x5612cc5d60e4 <unknown>
#9 0x5612cc5d70ae <unknown>
#10 0x5612cc899ce1 <unknown>
#11 0x5612cc89db7e <unknown>
#12 0x5612cc8874b5 <unknown>
#13 0x5612cc89e7d6 <unknown>
#14 0x5612cc86adbf <unknown>
#15 0x5612cc8c1748 <unknown>
#16 0x5612cc8c1917 <unknown>
#17 0x5612cc8d2773 <unknown>
#18 0x7f48b4e94ac3 <unknown>

2023-12-13 23:57:40 ERROR Unable to initialize WebDriver
2023-12-13 23:57:40 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 394, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcom-CcJ6hTD8-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5612cc8d35e3 <unknown>
#1 0x5612cc5960b7 <unknown>
#2 0x5612cc5e3f53 <unknown>
#3 0x5612cc5e4051 <unknown>
#4 0x5612cc6299c4 <unknown>
#5 0x5612cc60af1d <unknown>
#6 0x5612cc626b3d <unknown>
#7 0x5612cc60acc3 <unknown>
#8 0x5612cc5d60e4 <unknown>
#9 0x5612cc5d70ae <unknown>
#10 0x5612cc899ce1 <unknown>
#11 0x5612cc89db7e <unknown>
#12 0x5612cc8874b5 <unknown>
#13 0x5612cc89e7d6 <unknown>
#14 0x5612cc86adbf <unknown>
#15 0x5612cc8c1748 <unknown>
#16 0x5612cc8c1917 <unknown>
#17 0x5612cc8d2773 <unknown>
#18 0x7f48b4e94ac3 <unknown>

2023-12-13 23:57:47 ERROR Unable to initialize WebDriver
2023-12-13 23:57:47 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 394, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcom-CcJ6hTD8-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5612cc8d35e3 <unknown>
#1 0x5612cc5960b7 <unknown>
#2 0x5612cc5e3f53 <unknown>
#3 0x5612cc5e4051 <unknown>
#4 0x5612cc6299c4 <unknown>
#5 0x5612cc60af1d <unknown>
#6 0x5612cc626b3d <unknown>
#7 0x5612cc60acc3 <unknown>
#8 0x5612cc5d60e4 <unknown>
#9 0x5612cc5d70ae <unknown>
#10 0x5612cc899ce1 <unknown>
#11 0x5612cc89db7e <unknown>
#12 0x5612cc8874b5 <unknown>
#13 0x5612cc89e7d6 <unknown>
#14 0x5612cc86adbf <unknown>
#15 0x5612cc8c1748 <unknown>
#16 0x5612cc8c1917 <unknown>
#17 0x5612cc8d2773 <unknown>
#18 0x7f48b4e94ac3 <unknown>

2023-12-13 23:57:54 ERROR Unable to initialize WebDriver
2023-12-13 23:57:54 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 394, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcom-CcJ6hTD8-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5612cc8d35e3 <unknown>
#1 0x5612cc5960b7 <unknown>
#2 0x5612cc5e3f53 <unknown>
#3 0x5612cc5e4051 <unknown>
#4 0x5612cc6299c4 <unknown>
#5 0x5612cc60af1d <unknown>
#6 0x5612cc626b3d <unknown>
#7 0x5612cc60acc3 <unknown>
#8 0x5612cc5d60e4 <unknown>
#9 0x5612cc5d70ae <unknown>
#10 0x5612cc899ce1 <unknown>
#11 0x5612cc89db7e <unknown>
#12 0x5612cc8874b5 <unknown>
#13 0x5612cc89e7d6 <unknown>
#14 0x5612cc86adbf <unknown>
#15 0x5612cc8c1748 <unknown>
#16 0x5612cc8c1917 <unknown>
#17 0x5612cc8d2773 <unknown>
#18 0x7f48b4e94ac3 <unknown>

2023-12-13 23:58:00 ERROR Unable to initialize WebDriver
2023-12-13 23:58:00 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 82, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 394, in element_is_visible
    return Wait(self.browser, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcom-CcJ6hTD8-py3.11/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x5612cc8d35e3 <unknown>
#1 0x5612cc5960b7 <unknown>
#2 0x5612cc5e3f53 <unknown>
#3 0x5612cc5e4051 <unknown>
#4 0x5612cc6299c4 <unknown>
#5 0x5612cc60af1d <unknown>
#6 0x5612cc626b3d <unknown>
#7 0x5612cc60acc3 <unknown>
#8 0x5612cc5d60e4 <unknown>
#9 0x5612cc5d70ae <unknown>
#10 0x5612cc899ce1 <unknown>
#11 0x5612cc89db7e <unknown>
#12 0x5612cc8874b5 <unknown>
#13 0x5612cc89e7d6 <unknown>
#14 0x5612cc86adbf <unknown>
#15 0x5612cc8c1748 <unknown>
#16 0x5612cc8c1917 <unknown>
#17 0x5612cc8d2773 <unknown>
#18 0x7f48b4e94ac3 <unknown>