2025-05-24 02:57:30 ERROR Elements not present after 0.5 seconds on page: https://capital.com/en-gb
2025-05-24 02:57:30 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 86, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 340, in element_is_visible
    return Wait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x55867194471a <unknown>
#1 0x5586713e70a0 <unknown>
#2 0x5586714389b0 <unknown>
#3 0x558671438ba1 <unknown>
#4 0x558671486ea4 <unknown>
#5 0x55867145e3cd <unknown>
#6 0x5586714842a0 <unknown>
#7 0x55867145e173 <unknown>
#8 0x55867142ad4b <unknown>
#9 0x55867142b9b1 <unknown>
#10 0x5586719098cb <unknown>
#11 0x55867190d7ca <unknown>
#12 0x5586718f1622 <unknown>
#13 0x55867190e354 <unknown>
#14 0x5586718d645f <unknown>
#15 0x5586719324f8 <unknown>
#16 0x5586719326d6 <unknown>
#17 0x558671943586 <unknown>
#18 0x7f4b1249caa4 <unknown>
#19 0x7f4b12529c3c <unknown>

2025-05-24 02:57:41 ERROR Elements not present after 0.5 seconds on page: https://capital.com/ar-ae
2025-05-24 02:57:41 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 86, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 340, in element_is_visible
    return Wait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x55867194471a <unknown>
#1 0x5586713e70a0 <unknown>
#2 0x5586714389b0 <unknown>
#3 0x558671438ba1 <unknown>
#4 0x558671486ea4 <unknown>
#5 0x55867145e3cd <unknown>
#6 0x5586714842a0 <unknown>
#7 0x55867145e173 <unknown>
#8 0x55867142ad4b <unknown>
#9 0x55867142b9b1 <unknown>
#10 0x5586719098cb <unknown>
#11 0x55867190d7ca <unknown>
#12 0x5586718f1622 <unknown>
#13 0x55867190e354 <unknown>
#14 0x5586718d645f <unknown>
#15 0x5586719324f8 <unknown>
#16 0x5586719326d6 <unknown>
#17 0x558671943586 <unknown>
#18 0x7f4b1249caa4 <unknown>
#19 0x7f4b12529c3c <unknown>