2024-04-27 06:03:32 ERROR Elements not present after 0.5 seconds on page: https://capital.com/ar/trade-indices
2024-04-27 06:03:32 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 86, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 305, in element_is_visible
    return Wait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x556146f59cb3 <unknown>
#1 0x556146c484a7 <unknown>
#2 0x556146c9331d <unknown>
#3 0x556146c933d1 <unknown>
#4 0x556146cd6734 <unknown>
#5 0x556146cb543d <unknown>
#6 0x556146cd3be9 <unknown>
#7 0x556146cb51b3 <unknown>
#8 0x556146c8624a <unknown>
#9 0x556146c86c1e <unknown>
#10 0x556146f1dfdb <unknown>
#11 0x556146f21f2b <unknown>
#12 0x556146f0a0f1 <unknown>
#13 0x556146f22a92 <unknown>
#14 0x556146eeefaf <unknown>
#15 0x556146f48e08 <unknown>
#16 0x556146f48fe0 <unknown>
#17 0x556146f58e04 <unknown>
#18 0x7f14cfc94ac3 <unknown>

2024-04-27 06:03:40 ERROR Elements not present after 0.5 seconds on page: https://capital.com/trading/signup
2024-04-27 06:03:40 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 86, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 305, in element_is_visible
    return Wait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x556146f59cb3 <unknown>
#1 0x556146c484a7 <unknown>
#2 0x556146c9331d <unknown>
#3 0x556146c933d1 <unknown>
#4 0x556146cd6734 <unknown>
#5 0x556146cb543d <unknown>
#6 0x556146cd3be9 <unknown>
#7 0x556146cb51b3 <unknown>
#8 0x556146c8624a <unknown>
#9 0x556146c86c1e <unknown>
#10 0x556146f1dfdb <unknown>
#11 0x556146f21f2b <unknown>
#12 0x556146f0a0f1 <unknown>
#13 0x556146f22a92 <unknown>
#14 0x556146eeefaf <unknown>
#15 0x556146f48e08 <unknown>
#16 0x556146f48fe0 <unknown>
#17 0x556146f58e04 <unknown>
#18 0x7f14cfc94ac3 <unknown>

2024-04-27 06:03:43 ERROR Elements not present after 0.5 seconds on page: https://capital.com/trading/signup
2024-04-27 06:03:43 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 86, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 305, in element_is_visible
    return Wait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x556146f59cb3 <unknown>
#1 0x556146c484a7 <unknown>
#2 0x556146c9331d <unknown>
#3 0x556146c933d1 <unknown>
#4 0x556146cd6734 <unknown>
#5 0x556146cb543d <unknown>
#6 0x556146cd3be9 <unknown>
#7 0x556146cb51b3 <unknown>
#8 0x556146c8624a <unknown>
#9 0x556146c86c1e <unknown>
#10 0x556146f1dfdb <unknown>
#11 0x556146f21f2b <unknown>
#12 0x556146f0a0f1 <unknown>
#13 0x556146f22a92 <unknown>
#14 0x556146eeefaf <unknown>
#15 0x556146f48e08 <unknown>
#16 0x556146f48fe0 <unknown>
#17 0x556146f58e04 <unknown>
#18 0x7f14cfc94ac3 <unknown>

2024-04-27 06:03:46 ERROR Elements not present after 0.5 seconds on page: https://capital.com/trading/signup
2024-04-27 06:03:46 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 86, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 305, in element_is_visible
    return Wait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x556146f59cb3 <unknown>
#1 0x556146c484a7 <unknown>
#2 0x556146c9331d <unknown>
#3 0x556146c933d1 <unknown>
#4 0x556146cd6734 <unknown>
#5 0x556146cb543d <unknown>
#6 0x556146cd3be9 <unknown>
#7 0x556146cb51b3 <unknown>
#8 0x556146c8624a <unknown>
#9 0x556146c86c1e <unknown>
#10 0x556146f1dfdb <unknown>
#11 0x556146f21f2b <unknown>
#12 0x556146f0a0f1 <unknown>
#13 0x556146f22a92 <unknown>
#14 0x556146eeefaf <unknown>
#15 0x556146f48e08 <unknown>
#16 0x556146f48fe0 <unknown>
#17 0x556146f58e04 <unknown>
#18 0x7f14cfc94ac3 <unknown>

2024-04-27 06:03:49 ERROR Elements not present after 0.5 seconds on page: https://capital.com/trading/signup
2024-04-27 06:03:49 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 86, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 305, in element_is_visible
    return Wait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x556146f59cb3 <unknown>
#1 0x556146c484a7 <unknown>
#2 0x556146c9331d <unknown>
#3 0x556146c933d1 <unknown>
#4 0x556146cd6734 <unknown>
#5 0x556146cb543d <unknown>
#6 0x556146cd3be9 <unknown>
#7 0x556146cb51b3 <unknown>
#8 0x556146c8624a <unknown>
#9 0x556146c86c1e <unknown>
#10 0x556146f1dfdb <unknown>
#11 0x556146f21f2b <unknown>
#12 0x556146f0a0f1 <unknown>
#13 0x556146f22a92 <unknown>
#14 0x556146eeefaf <unknown>
#15 0x556146f48e08 <unknown>
#16 0x556146f48fe0 <unknown>
#17 0x556146f58e04 <unknown>
#18 0x7f14cfc94ac3 <unknown>

2024-04-27 06:03:52 ERROR Elements not present after 0.5 seconds on page: https://capital.com/trading/signup
2024-04-27 06:03:52 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 86, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 305, in element_is_visible
    return Wait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x556146f59cb3 <unknown>
#1 0x556146c484a7 <unknown>
#2 0x556146c9331d <unknown>
#3 0x556146c933d1 <unknown>
#4 0x556146cd6734 <unknown>
#5 0x556146cb543d <unknown>
#6 0x556146cd3be9 <unknown>
#7 0x556146cb51b3 <unknown>
#8 0x556146c8624a <unknown>
#9 0x556146c86c1e <unknown>
#10 0x556146f1dfdb <unknown>
#11 0x556146f21f2b <unknown>
#12 0x556146f0a0f1 <unknown>
#13 0x556146f22a92 <unknown>
#14 0x556146eeefaf <unknown>
#15 0x556146f48e08 <unknown>
#16 0x556146f48fe0 <unknown>
#17 0x556146f58e04 <unknown>
#18 0x7f14cfc94ac3 <unknown>

2024-04-27 06:03:55 ERROR Elements not present after 0.5 seconds on page: https://capital.com/trading/signup
2024-04-27 06:03:55 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 86, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 305, in element_is_visible
    return Wait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x556146f59cb3 <unknown>
#1 0x556146c484a7 <unknown>
#2 0x556146c9331d <unknown>
#3 0x556146c933d1 <unknown>
#4 0x556146cd6734 <unknown>
#5 0x556146cb543d <unknown>
#6 0x556146cd3be9 <unknown>
#7 0x556146cb51b3 <unknown>
#8 0x556146c8624a <unknown>
#9 0x556146c86c1e <unknown>
#10 0x556146f1dfdb <unknown>
#11 0x556146f21f2b <unknown>
#12 0x556146f0a0f1 <unknown>
#13 0x556146f22a92 <unknown>
#14 0x556146eeefaf <unknown>
#15 0x556146f48e08 <unknown>
#16 0x556146f48fe0 <unknown>
#17 0x556146f58e04 <unknown>
#18 0x7f14cfc94ac3 <unknown>