2024-02-16 14:00:49 ERROR Elements not present after 0.5 seconds on page: https://capital.com/
2024-02-16 14:00:49 ERROR Can't see element by locator ('css selector', "iframe[title='reCAPTCHA']")
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 84, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 517, in is_captcha
    if self.elements_are_visible(Captcha.CAPTCHA_IFRAME):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 637, in elements_are_visible
    return Wait(self.driver, timeout).until(EC.visibility_of_any_elements_located(locator),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: Can't see element by locator ('css selector', "iframe[title='reCAPTCHA']")

2024-02-16 14:01:10 ERROR Elements not present after 0.5 seconds on page: https://capital.com/fibonnaci-retracement
2024-02-16 14:01:10 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 84, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 301, in element_is_visible
    return Wait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x55a814f58d93 <unknown>
#1 0x55a814c3c337 <unknown>
#2 0x55a814c87d60 <unknown>
#3 0x55a814c87e51 <unknown>
#4 0x55a814ccbbc4 <unknown>
#5 0x55a814caa46d <unknown>
#6 0x55a814cc912d <unknown>
#7 0x55a814caa1e3 <unknown>
#8 0x55a814c7a135 <unknown>
#9 0x55a814c7b13e <unknown>
#10 0x55a814f1ce4b <unknown>
#11 0x55a814f20dfa <unknown>
#12 0x55a814f096d5 <unknown>
#13 0x55a814f21a6f <unknown>
#14 0x55a814eed69f <unknown>
#15 0x55a814f46098 <unknown>
#16 0x55a814f46262 <unknown>
#17 0x55a814f57f34 <unknown>
#18 0x7feefd894ac3 <unknown>

2024-02-16 14:01:13 ERROR Elements not present after 0.5 seconds on page: https://capital.com/fibonnaci-retracement
2024-02-16 14:01:13 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 84, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 301, in element_is_visible
    return Wait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x55a814f58d93 <unknown>
#1 0x55a814c3c337 <unknown>
#2 0x55a814c87d60 <unknown>
#3 0x55a814c87e51 <unknown>
#4 0x55a814ccbbc4 <unknown>
#5 0x55a814caa46d <unknown>
#6 0x55a814cc912d <unknown>
#7 0x55a814caa1e3 <unknown>
#8 0x55a814c7a135 <unknown>
#9 0x55a814c7b13e <unknown>
#10 0x55a814f1ce4b <unknown>
#11 0x55a814f20dfa <unknown>
#12 0x55a814f096d5 <unknown>
#13 0x55a814f21a6f <unknown>
#14 0x55a814eed69f <unknown>
#15 0x55a814f46098 <unknown>
#16 0x55a814f46262 <unknown>
#17 0x55a814f57f34 <unknown>
#18 0x7feefd894ac3 <unknown>

2024-02-16 14:01:16 ERROR Elements not present after 0.5 seconds on page: https://capital.com/fibonnaci-retracement
2024-02-16 14:01:16 ERROR 
Traceback (most recent call last):
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 84, in inner_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/TestCapitalComPySe/TestCapitalComPySe/pages/base_page.py", line 301, in element_is_visible
    return Wait(self.driver, timeout).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/testcapitalcompyse-CcJ6hTD8-py3.12/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x55a814f58d93 <unknown>
#1 0x55a814c3c337 <unknown>
#2 0x55a814c87d60 <unknown>
#3 0x55a814c87e51 <unknown>
#4 0x55a814ccbbc4 <unknown>
#5 0x55a814caa46d <unknown>
#6 0x55a814cc912d <unknown>
#7 0x55a814caa1e3 <unknown>
#8 0x55a814c7a135 <unknown>
#9 0x55a814c7b13e <unknown>
#10 0x55a814f1ce4b <unknown>
#11 0x55a814f20dfa <unknown>
#12 0x55a814f096d5 <unknown>
#13 0x55a814f21a6f <unknown>
#14 0x55a814eed69f <unknown>
#15 0x55a814f46098 <unknown>
#16 0x55a814f46262 <unknown>
#17 0x55a814f57f34 <unknown>
#18 0x7feefd894ac3 <unknown>